org: guivarela
app: bestsellers
service: bestsellers
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: '20201221'
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: products/create.create
    events:  
      - httpApi:
          path: /products
          method: post

  list:
    handler: products/list.list
    events:
      - httpApi:
          path: /products
          method: get

  get:
    handler: products/get.get
    events:
      - httpApi:
          path: /products/{id}
          method: get

  update:
    handler: products/update.update
    events:
      - httpApi:
          path: /products/{id}
          method: put

  delete:
    handler: products/delete.delete
    events:
      - httpApi:
          path: /products/{id}
          method: delete

resources:
  Resources:
    ProductsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}